### ISSUE TITLE
Re-write description of our meetups

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#21]
See the "Advertising of meetups" section of the proposal https://github.com/foundersandcoders/london-programme/issues/149#issue-200398148

Feel free to ask me if you have any questions

**Comment by joeylouise** [comment]
Thanks @jsms90 - do @PiotrBerebecki and I need admin access to the meetup page? Maybe a question for @sofer?

**Comment by jsms90** [comment]
@joeylouise You're both event organisers already :+1:

**Comment by joeylouise** [comment]
@jsms90 thanks! 😄

**Comment by jsms90** [comment]
https://docs.google.com/document/d/1IPVmyrq4Iy_fPAjmqqGeV89QNXDk-_YAT-wZHzsciVA/edit#

**Comment by PiotrBerebecki** [comment]
@joeylouise and I have just drafted a description for the C4E meetups:

Come and join us for our regular Monday evening meetup and participate in any one of a number of peer-led JavaScript coding activities, including:

- Free Code Camp projects;
- Solving and creating Codewars katas;
- Working on your application for Founders & Coders.
- Codecademy
- Eloquent Javascript
- CS50

This meetup is for everyone who wants to learn to code. During the meetup we encourage participants to work together with another meetup attendee on one laptop (pair programming). Students from the current cohort of Founders & Coders will be available for questions and support.

Please note that laptops aren't provided, but since we encourage pair programming you are welcome to join us without a laptop and work with another participant.

Founders and Coders, Code of Conduct:
https://github.com/codingforeveryone/code-of-conduct
Our community is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of community members in any form. Participants violating these rules may be sanctioned or expelled from the event and any future events, as well as from the community itself.

**Comment by jsms90** [comment]
+ "Working on your application for Founders & Coders" has been removed, as we don't have any trouble attracting those who are applying to the course. Whereas C4E is often seen as exclusively for applicants.
+ We could include links to the relevant websites for each of the bullet points, for anyone who isn't familiar with these resources

@PiotrBerebecki This looks good. Let's change the description on meetup.com asap :+1:

**Comment by jsms90** [comment]
Messages need to be sent round to those who have already clicked "attending" on the Coding Bookclub meetups, before we delete them.

**Comment by joeylouise** [comment]
@PiotrBerebecki and I have now updated C4E description
e.g. https://www.meetup.com/founderscoders/events/237650863/

**Comment by joeylouise** [comment]
And now updated C4W as well

**Comment by jsms90** [comment]
@joeylouise @PiotrBerebecki I've updated your roles on meetup.com, so you should be able to see and reply to messages now.

Wanna send around that message to people who are "attending" the other meetups of ours that we will be deleting (e.g. Eloquent Javascript Bookclub)?

**Comment by PiotrBerebecki** [comment]
@joeylouise and I just messaged attendees and invited them to join us for Coding for Everyone on Mondays 😀 All done 👍 Shall we close this issue now?
